compile_pdf:
  stage: build
  image: thomasweise/texlive    # use a Docker image for LaTeX from https://hub.docker.com/
  script: xelatex cv.tex        # build the pdf just as you would on your computer
  artifacts:
    paths: 
      - cv.pdf                  # instruct GitLab to keep the cv.pdf file

pages:
  stage: deploy
  script:
    - mkdir public        # create a folder called public
    - mv cv.pdf public    # copy the pdf file into the public folder
  artifacts:
    paths:
      - public            # instruct GitLab to keep the public folder
  only:
    - master              # Only for the master branch 
